### PR TITLE
kasey bugs

### LINKED ISSUE #521: data table header demo, you have to click each header twice before the sort arrow appears (bind in default sort?)

### PR DESCRIPTION
**Pull request by kaseyhinton**
closes #521
fixes manual address dialog using a file it doesn't have access to

### CODE REVIEW

File: packages/web/titanium/address-input/manual-address-dialog.ts [hunk 1]
```diff
@@ -72,12 +71,32 @@ export class ManualAddressDialog extends LitElement {
...
+        align-items: center;
+        justify-self: start;
+        user-select: none;
+      }
+
+      @media (max-width: 786px) {
+        form {
+          display: flex;
+          flex-direction: column;
+        }
```
Comment (aarondrabeck) [inline packages/web/titanium/address-input/manual-address-dialog.ts:98]: I do not think we need all these styles, the dialog cannot exceed 550px

**Review by aarondrabeck — APPROVED** [review]

**Review by antwonthegreat — APPROVED** [review]
