### PR TITLE
Multi-issues fixed

### LINKED ISSUE #323: titanium-attachment-input is case insensitive when letting you pick a file with an extension but will not actually select a file when the case doesn't match

### LINKED ISSUE #329: titanium-data-table-item get items() should fall back to return an empty array
Other spots in the class assume it exists and will throw if an item is not provided

### LINKED ISSUE #332: titanium-data-table accesses this.pageControl without null checking, it can be null if disablePaging is set to true

### LINKED ISSUE #341: many of the jsdocs say "Displays error state if no image is empty and input is blurred.", this was mistakenly copied from titanium-image-input

### LINKED ISSUE #354: leavitt-person-company-select Person and Company props should be Partial

### LINKED ISSUE #361: can't find address modal in titanium-address-input needs to fix label floating when prefilled

### PR DESCRIPTION
**Pull request by aarondrabeck**
closes #332
closes #354
closes #341
closes #323
closes #361
closes #329

### CODE REVIEW

**Review by kaseyhinton — APPROVED** [review]

File: packages/leavittbook/src/demos/titanium-address-input/titanium-address-input-playground.ts [hunk 1]
```diff
@@ -57,44 +71,38 @@ export class TitaniumAddressInputPlayground extends LitElement {
       <h1>Default</h1>
       <p>Examples using default, required, outlined, icon, helper, and helperPersistent</p>
```
Comment (antwonthegreat) [inline packages/leavittbook/src/demos/titanium-address-input/titanium-address-input-playground.ts:72]: This description should be updated if the demos for the props are being removed

**Review by antwonthegreat — APPROVED** [review]

**Review by ShawnJohnson14 — APPROVED** [review]
